# docker-compose.yml
version: '3.8'

services:
  # -------------------------------
  # Supabase core services
  # -------------------------------
  db:
    image: supabase/postgres:15.2.0
    env_file:
      - .env
    volumes:
      - supabase_data:/var/lib/postgresql/data

  auth:
    image: supabase/gotrue:latest
    env_file:
      - .env
    depends_on:
      - db

  postgrest:
    image: supabase/postgrest:latest
    env_file:
      - .env
    depends_on:
      - db

  realtime:
    image: supabase/realtime:latest
    env_file:
      - .env
    depends_on:
      - db

  storage:
    image: supabase/storage:latest
    env_file:
      - .env
    depends_on:
      - db

  studio:
    image: supabase/studio:latest
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - auth

  # -------------------------------
  # MQTT broker
  # -------------------------------
  mosquitto:
    image: eclipse-mosquitto:2.0
    env_file:
      - .env
    ports:
      - '${MQTT_PORT}:1883'
      - '${MQTT_WS_PORT}:8080'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # -------------------------------
  # Your CameraGuardAI service
  # -------------------------------
  camera-guard:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - mosquitto
    ports:
      - '5000:5000'

volumes:
  supabase_data:
